### ISSUE TITLE
Printar JSON från borsdata_api när man kör history_kpi från borsdata_client

### ISSUE THREAD

**Issue by aeson1** [TapeReaderJoe/BorsdataAPI#1]
https://github.com/TapeReaderJoe/BorsdataAPI/blob/57a24e4342f340cd9cd1124e81041814ae6585d9/borsdata/borsdata_api.py#L122

Blir väldigt stökigt i output

**Comment by TapeReaderJoe** [comment]
En gammal debug-print, fixar till det!
