### ISSUE TITLE
Sätta upp rätt miljö

### ISSUE THREAD

**Issue by davlov** [TapeReaderJoe/BorsdataAPI#2]
Hej,

Jag gjorde allting enligt beskrivningen, men jag får följande felmeddelande:

from borsdata.borsdata_api import *
ModuleNotFoundError: No module named 'borsdata'

Kan ni hjälpa mig klura ut varför jag får detta felmeddelande? Kan det vara att saker och ting ligger på fel ställen? Eller att jag missat något vid installationen?

Också, kan man använda Spyder istället för PyCharm? Jag är mer van vid Spyder miljön.

Tack!

**Comment by TapeReaderJoe** [comment]
Hej,

Du har inte råkat byta namn på mappen? borsdata är nämligen mappen som borsdata_api.py återfinns i.
Det du kan göra är att testa ta bort borsdata, då klienten återfinns i samma mapp borde den hitta den ändå.

`from borsdata.borsdata_api import *`
-> `from borsdata_api import *`

Det kan vara så att Spyder inte sätter rätt path för projektet, att det är det som även ger "ModuleNotFoundError". Har själv ingen vana av Spyder men det borde gå lika bra som PyCharm.

/Johan

**Comment by davlov** [comment]
Hej,

Tack för det snabba svaret!
Jag insåg att jag inte "öppnade" projektet på rätt sätt. 
Nu har den uppdaterat alla versioner enligt kraven och den verkar ha länkat korrekt, men jag får ett nytt problem när jag kör borsdata_client

import pandas._libs.window.aggregations as window_aggregations
ImportError: DLL load failed while importing aggregations: Det går inte att hitta den angivna modulen.

Vad kan denna bero på?
Tack

**Comment by TapeReaderJoe** [comment]
Inget problem jag känner till men en snabb sökning verkar peka på Pandas-biblioteket, testa en ominstallation av Pandas (avinstallera och installera igen).

Om du använder pip:
`pip uninstall pandas`
`pip install pandas`

Lycka till!

**Comment by davlov** [comment]
Tack Johan!
Nu funkar det med pandas-1.2.2
:)

**Comment by TapeReaderJoe** [comment]
Nice!

Stänger issuen, finns även på Twitter under TapeReaderJoe om du behöver allmän Python-assistans! :)

/Johan
