### ISSUE TITLE
borsdata_client not aligned with new borsdata_api

### ISSUE THREAD

**Issue by andersborgabiro** [TapeReaderJoe/BorsdataAPI#5]
The API abstraction now uses indices that borsdata_client is not updated for.

Also, I needed to change "from borsdata import..." to just "import...".

get_instrument_name is used but doesn't exist.

**Comment by TapeReaderJoe** [comment]
Thank you Anders, I'll try to fix that asap!

**Comment by TapeReaderJoe** [comment]
Made a quick refactoring, hopefully everything works "as before".

BR, Johan

**Comment by andersborgabiro** [comment]
Great. Will test it.

**Comment by andersborgabiro** [comment]
So you kept the abstraction as-is and changed ...client only?

Any thoughts of a second example that does this (as a tutorial):
* Inputs a ticker or company name
* Outputs that company's stats and the last month(s) stock prices (day) as a candlestick chart (start, end, lowest, highest)

I know I can make this easily myself, but it would be a great (and quickly run) example.

Frankly I don't know what is the practical use of the current example, except testing the abstraction. Some kind of overall market trend? Any hints :)?

**Comment by TapeReaderJoe** [comment]
The clients intention is to show examples of practical uses of the API. Hence it is hard to cover all possible use-cases ;) My code base is a lot bigger than the client examples shown here, so it is up to the API-user I guess.

BR, Johan.

**Comment by andersborgabiro** [comment]
First, I still needed to remove "from borsdata" in client and api to run the code as-is. The rest worked fine.

"hard to cover all possible use-cases" and "show examples of practical uses of the API"

It depends on what you mean by practical. It sure tests the crap out of the API and the Börsdata service. Is it a real investment use case though?
